language: cpp

sudo: false

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake

before_install:
  - git clone git@github.com:CxxTest/cxxtest.git cxxtest
  - cmake --version

script:
  - mkdir -p project1/build
  - cd project1/build
  - cmake -DCMAKE_PREFIX_PATH=${PWD}/../../cxxtest/ ..
  - make
  - ./cxxtests -v
  - ./Test

notifications:
  email:
    on_success: change
    on_failure: change
