language: cpp

sudo: false

before_install:
  - git clone git@github.com:CxxTest/cxxtest.git cxxtest
  - export PATH=$PATH:$PWD/cxxtest/bin/

script:
  - cd project1
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./cxxtests -v
  - ./Test

notifications:
  email:
    on_success: change
    on_failure: change
