language: cpp

sudo: true

before_install:
  - git clone git@github.com:CxxTest/cxxtest.git cxxtest
  - yes | sudo add-apt-repository ppa:kalakris/cmake
  - sudo apt-get update -qq

install:
  - sudo apt-get install cmake
  - cmake --version

script:
  - mkdir -p project1/build
  - cd project1/build
  - cmake -DCMAKE_PREFIX_PATH=${PWD}/../../cxxtest/ ..
  - make
  - ./cxxtests -v
  - ./Test

notifications:
  email:
    on_success: change
    on_failure: change
